Repository kids-first/kf-portal-ui, pull requests merged in 2020-03, with the labels that each got.

#2357 fix(update): #2329 package updates
  package-lock.json
  package.json
Labels: maintenance

#2364 fix(report member dlg): remove capital letter 'm'
  src/components/UserProfile/ReportMemberDlg.js
Labels: ui

#2377 fix: #2300 update eslint and prettier for auto formatting
  .eslintrc.json
  package-lock.json
  package.json
Labels: productivity
